### ISSUE TITLE
Exercise 13.4.3 explain why you use 2013

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#132]
I can understand your use `2013 - year` to compute the age. But at the first glance, I wonder why you use `2013`, not something like `2015`, `2018`. Would that results in negative number?

Maybe you can add this line from nycflights13 DESCRIPTION
> Airline on-time data for all flights departing NYC in 2013

**Comment by jrnold** [comment]
Good note. I should use the year of the flight instead of hard-coding it.

**Comment by Youguang** [comment]
There are missing values in dep_delay/arr_delay, so the "n" used for calculating standard error should be "sum(!is.na(dep_delay))".
And why use 4 times standard error to plot? 
> ymin = dep_delay_mean - 2 * dep_delay_sd / sqrt(n),
    ymax = dep_delay_mean + 2 * dep_delay_sd / sqrt(n)

**Comment by jrnold** [comment]
Thanks! I corrected the `n()`. I was using standard errors because they convey uncertainty about the mean. I removed those since standard errors aren't introduced in the book. I changed to the plot to censor plane ages at 25, which handles the issue that I was most concerned about, each age in the right tail consisting of only a few observations.
