### ISSUE TITLE
Exercise 13.5.4: cross-reference delay with the `weather` data

### ISSUE THREAD

**Issue by dongzhuoer** [jrnold/r4ds-exercise-solutions#135]
The question says

> Find the 48 hours (over the course of the whole year) that have the worst delays. Cross-reference it with the weather data. Can you see any patterns?

In your anwer

```r
flights %>%
  group_by(year, month, day) %>%
  summarise(total_24 = sum(dep_delay, na.rm = TRUE)+ sum(arr_delay, na.rm = TRUE)) %>%
  mutate(total_48 = total_24 + lag(total_24)) %>%
  arrange(desc(total_48))
```

- Why do you add `dep_delay` and `arr_delay`?
- I think you should use `mean()` rather than `sum()` to find worst delay
- The question requires to  cross-reference delay with the `weather` data. (I tried it but failed to find an obvious pattern)

**Comment by jrnold** [comment]
> - Why do you add `dep_delay` and `arr_delay`?
> - I think you should use `mean()` rather than `sum()` to find worst delay

I think my thinking was that what matters is the "total" delay for all people, which would be the delay per flight x flights delays, which is why I use sum instead of mean. But the mean is also a reasonable way to answer the question. Neither is wrong, they are just different ways of operationalizing what is meant by "worst".  

However, summing the departure delay and arrival delay doesn't do what I was thinking. It should be departure or arrival delay, or both.

> - The question requires to  cross-reference delay with the `weather` data. (I tried it but failed to find an obvious pattern)

Oops. Do you have code for that? What did you do? Nothing came up for June 12-13, when there was a derecho? (Ex 13.4.6.5)

**Comment by jrnold** [comment]
Now I'm trying to understand what this question is even asking. It is ambiguously worded. Given what the chapter is about and the tools introduced so far, it seems like the answer should involve simply merging the flight data with the hourly weather data. I think the "48 hours over the whole year" means 48 hourly observations and not a single 48-hour stretch. To do the later would require using window functions not introduced in the book.
