### ISSUE TITLE
5.2.4 excercise 1.5 and 1.6

### ISSUE THREAD

**Issue by JamesCuster** [jrnold/r4ds-exercise-solutions#29]
Question: Arrived more than two hours late, but didn’t leave late
answer provided:
filter(flights, !is.na(dep_delay), dep_delay <= 0, arr_delay > 120)

This works properly, but the !is.na(dep_delay) is not needed. filter only includes rows for which the condition is true. 

From the R4DS text: "filter() only includes rows where the condition is TRUE; it excludes both FALSE and NA values."

question 1.6 has the same issue.
question: Were delayed by at least an hour, but made up over 30 minutes in flight
provided answer:
filter(flights, !is.na(dep_delay),
       dep_delay >= 60, dep_delay - arr_delay > 30)

**Comment by jrnold** [comment]
No, the `!is.na(delay)` is not needed. Many years of being burned by `NA` values in logical comparisons in R created a habit of always including that comparison just to be safe.

**Comment by JamesCuster** [comment]
That is fair, I am used to using it as well. This is my introduction to the basics of dplyr, and I got to say I don't care for that behavior. I suppose it is just because I am used to my way.

I don't know if it is appropriate to ask on here, but I want to see what your opinion is. I am able to do all this stuff that these basic dplyr functions do with base R. Is there any reason to be using dplyr versus what is available in base R? Is there a speed improvement? Do you know if people in the workforce prefer using the tidyverse instead of base R? I guess I am wondering cause I hear a lot of chatter about the tidyverse and I wonder whats the point of using it if I can do it without an additional package.

**Comment by jrnold** [comment]
I actually like that behavior. I understand why R doesn't treat `FALSE & NA` as `FALSE`, but for filtering, dropping `NA` by default seems the right choice.

Having used R prior to tidyverse, I'm all in. Yes, you can do all of it with base, but Turing completeness means you can do anything in R in assembly and no sane person would do that. It's not faster computationally; it's probably a little slower in some places because some more things are implicit. But in what matters most of the time, I find it more concise and clear to read and write code, and thus I'm much more productive using it.

**Comment by JamesCuster** [comment]
I see. Thank you for your input. This was part of the reason that I felt it would be beneficial for me to learn so this just affirms that. As I am working through the book I am noticing that I like the way the code reads better. Especially once you start to incorporate pipping.
