### ISSUE TITLE
Exercise 14.4.3.2: improve answer. Seperating the pieces before and after the apostrophe.

### ISSUE THREAD

**Issue by neander09** [jrnold/r4ds-exercise-solutions#313]
The answer could be improved by really seperating out the pieces before and after the apostrophe with str_match for example.

**Comment by MarvinMainz** [comment]
@jrnold 
Hi I wanted to open a new issue because of this, but I willl first try to reach out by commenting on this issue.

The subsection to which this exercise is related to introduced `str_match() `and `str_match_all()`. Thus, the answer that the book wants to be given is certainly not a two-step processes which does not involve either function, but rather as @neander09 suggested the use of `str_match_all()`.

I used this code and it did the trick:
`str_match_all(sentences, "([A-Za-z]+)'([A-Za-z]+)")`
