### ISSUE TITLE
Exercise 5.5.4 Shorter ways to solve it

### ISSUE THREAD

**Issue by martinruhle** [jrnold/r4ds-exercise-solutions#362]
I've used three ways to solve this Exercise.

# The more intuitive one I think is this one:

flights %>%
  arrange(desc(dep_delay)) %>%
  slice(1:10)

# The shortest one, probably is this one:

top_n(flights, 10, dep_delay) %>%
  arrange(desc(dep_delay))

# Finally if we want to use the min_rank function learned in the chapter we can use:

filter(flights, min_rank(desc(dep_delay)) <= 10) %>%
  arrange(desc(dep_delay))

**Comment by jrnold** [comment]
Nice examples. I added a section at the end of the question that discusses using non-ranking functions to answer the question.

The question itself explicitly asks to use ranking functions. The examples are also a  little more verbose than they need to be because `%>%` isn't introduced until the next section.
